parameters:
# ⚠ must be dependant on a stage exporting CurrentPullRequestAttributes.JiraIdList
- name: dependsOn
  type: object
  default: tagging
- name: repositoryAlias
  type: string
  default: 'happy-jira-link'
- name: organizationName
  type: string
  default: 'axafrance'
- name: projectName
  type: string
  default: 'MyProject'
- name: jira
  type: object
  default:
    # The group must contain a variable called "jira_pat" (the PAT as a secret)
    variableGroup: 'olisail-jira-pat-group'
    baseUrl: 'https://jira.my.intranet'
    cardFieldKeys:
      appCode: 'customfield_16801'
      tribe: 'customfield_27500'
      domain: 'customfield_27501'
      squad: 'customfield_27502'
    cardFieldValues:
      projectId: '12345'
      appCode: '12345'
      tribeId: '12345'
      domainId: '12345'
      squadId: '12345'
    ticketStatusIds:
      codeReviewInProgress: '12345'
      codeReviewDone: '12345'

stages:
- stage: jira
  displayName: 'JIRA Processing'
  dependsOn: ${{ parameters.dependsOn }}
  jobs:  
  - template: process-jira-status.yml
    parameters:
      repositoryAlias: ${{ parameters.repositoryAlias }}
      organizationName: ${{ parameters.organizationName }}
      projectName: ${{ parameters.projectName }}
      jira: ${{ parameters.jira }}
  - template: tag-pullrequest.yml
    parameters:
      repositoryAlias: ${{ parameters.repositoryAlias }}
      organizationName: ${{ parameters.organizationName }}
      projectName: ${{ parameters.projectName }}